FROM php:8.2-fpm

# ENV APP_URL ${APP_URL}
# ENV DB_HOST ${POSTGRES_HOST}
# ENV DB_PORT ${POSTGRES_PORT}
# ENV DB_DATABASE ${POSTGRES_DB}
# ENV DB_USERNAME ${POSTGRES_USER}
# ENV DB_PASSWORD ${POSTGRES_PASSWORD}
# ENV ELASTICSEARCH_USERNAME ${ELASTIC_USERNAME}
# ENV ELASTICSEARCH_PASSWORD ${ELASTIC_PASSWORD}
# ENV ELASTICSEARCH_ENABLED ${ELASTICSEARCH_ENABLED}
# ENV ELASTICSEARCH_HOSTS ${ELASTICSEARCH_HOSTS}
# ENV QUEUE_CONNECTION ${QUEUE_CONNECTION}
# ENV REDIS_HOST ${REDIS_HOST}
# ENV REDIS_CLIENT ${REDIS_CLIENT}
# ENV REDIS_PORT ${REDIS_PORT}

RUN cd /tmp \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

RUN apt-get update

COPY php.ini /usr/local/etc/php/conf.d/

RUN apt-get -y install --fix-missing \
    apt-utils \
    build-essential \
    git \
    curl \
    libcurl4 \
    libcurl4-openssl-dev \
    zlib1g-dev \
    libzip-dev \
    zip \
    libbz2-dev \
    locales \
    libmcrypt-dev \
    libicu-dev \
    libonig-dev \
    libxml2-dev

RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql bcmath pgsql

RUN pecl install redis \
    && docker-php-ext-enable redis

