version: "3"
services:
  db:
    image: postgres:16-alpine
    restart: always
    deploy:
        replicas: 1
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.5"
                memory: "512M"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    networks:
      - db-net

  nginx:
    image: mlcity_nginx
    deploy:
        replicas: 1
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.1"
                memory: "256M"
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
        - "${APP_PORT}:443"
    depends_on:
        - backend
    volumes:
        - ../:/var/www/MLCity_backend
        - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - ng-net

  backend:
    image: mlcity_laravel
    deploy:
        replicas: 1
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.5"
                memory: "512M"
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - "../:/var/www/MLCity_backend"
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_HOSTS=elasticsearch:${ELASTIC_PORT}
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=cache
      - REDIS_CLIENT=phpredis
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - cache-net
      - db-net
      - es-net
      - ng-net
    ports:
      - "9000:9000"
    working_dir: /var/www/MLCity_backend
    # command: composer install && php artisan migrate

  worker:
    image: mlcity_worker
    restart: always
    deploy:
        replicas: 10
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.2"
                memory: "256M"
    command: php artisan queue:work --daemon
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - "../:/var/www/MLCity_backend"
    environment:
      - APP_URL=${APP_URL}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_HOSTS=elasticsearch:${ELASTIC_PORT}
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=cache
      - REDIS_CLIENT=phpredis
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - cache-net
      - db-net
      - es-net
    working_dir: /var/www/MLCity_backend

  elasticsearch:
    image: elasticsearch:8.15.3
    deploy:
        replicas: 1
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.3"
                memory: "256M"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    ports:
      - "${ELASTIC_PORT}:9200"
      - "9300:9300"
    networks:
      - es-net
  kibana:
    image: kibana:8.15.3
    deploy:
        replicas: 1
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.5"
                memory: "512M"
    environment:
      - xpack.monitoring.enabled=true         # Включить мониторинг
      - xpack.security.enabled=false          # Включить безопасность
      - xpack.reporting.enabled=true         # Включить отчёты
      - xpack.graph.enabled=true             # Включить графики
      - ELASTICSEARCH_URL=https://elasticsearch:${ELASTIC_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - es-net
    depends_on:
      - elasticsearch

  cache:
    image: redis:6.2-alpine
    deploy:
        replicas: 1
        restart_policy:
            delay: 5s
            condition: on-failure
        resources:
            limits:
                cpus: "0.5"
                memory: "512M"
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - cache-net

networks:
  db-net:
  es-net:
  ng-net:
  cache-net:

#volumes:
#  esdata1:
#    driver: local
