services:
  db:
    image: postgres
    container_name: MLCity_database
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
        - "8000:80"
    depends_on:
        - backend
        - db
    volumes:
        - ../:/var/www/MLCity_backend
        - ./nginx/conf.d/:/etc/nginx/conf.d

  backend:
    container_name: MLCity_backend
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - "../:/var/www/MLCity_backend"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      # - APP_URL=http://localhost:9090
    ports:
      - "9000:9000"
    working_dir: /var/www/MLCity_backend
    # command: composer install && php artisan migrate


  # build-admin:
  #   depends_on:
  #     - backend
  #     - nginx
  #   build:
  #     context: ./php
  #     dockerfile: admin.dockerfile
  #   volumes:
  #     - "../:/var/www/MLCity_backend"
  #   working_dir: /var/www/MLCity_backend

  artisan:
    depends_on:
      - backend
    build:
      context: ./php
      dockerfile: dockerfile
    volumes:
      - "../:/var/www/MLCity_backend"
    working_dir: /var/www/MLCity_backend
    entrypoint: ["/bin/bash"]
    command: ["-c", "composer install && php artisan migrate && php artisan db:seed"]

