<?php

declare(strict_types=1);

namespace App\MoonShine\Pages\MoonPlace;

use MoonShine\Contracts\MoonShineRenderable;
use MoonShine\Fields\Fields;
use MoonShine\Fields\ID;
use MoonShine\Fields\Number;
use MoonShine\Fields\Text;
use MoonShine\Pages\Crud\IndexPage;
use MoonShine\Components\MoonShineComponent;
use MoonShine\Fields\Field;
use MoonShine\Decorations\Collapse;
use Throwable;

class MoonPlaceIndexPage extends IndexPage
{
    use MoonPlaceHelperPageTrait;
    /**
     * @return list<MoonShineComponent|Field>
     */
    public function fields(): array
    {
        return [
            ID::make()->sortable(),
            Number::make('Долгота', 'latitude'),
            Number::make('Широта', 'longitude'),
            Text::make('Адрес', 'address'),
            $this->showSeances(),

        ];
    }
    protected function itemsComponent(iterable $items, Fields $fields): MoonShineRenderable
    {
        $components = [];
        !empty($items->longitude) ? $components[] = Number::make('Долгота')->default(fn($items) => $items->latitude) : null;
        !empty($items->longitude) ? $components[] = Number::make('Широта')->default(fn($items) => $items->longitude): null;
        !empty($items->longitude) ? $components[] =  Text::make('Адрес')->default(fn($items) => $items->address): null;

        return Collapse::make('Место провидения')->fields($components)->persist(fn() => false);
        // TODO: Change the autogenerated stub (change table)
    }

    /**
     * @return list<MoonShineComponent>
     * @throws Throwable
     */
    protected function topLayer(): array
    {
        return [
            ...parent::topLayer()
        ];
    }

    /**
     * @return list<MoonShineComponent>
     * @throws Throwable
     */
    protected function mainLayer(): array
    {
        return [
            ...parent::mainLayer()
        ];
    }

    /**
     * @return list<MoonShineComponent>
     * @throws Throwable
     */
    protected function bottomLayer(): array
    {
        return [
            ...parent::bottomLayer()
        ];
    }
}
