name : 'MLCity Backend develop server deploy'

on:
  push:
    branches: ["develop"]

jobs:
  re-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          password: ${{ secrets.DEV_PASS }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE }}

          script: |
            cd ${{ secrets.DEV_DIR }};
            git checkout develop;
            git pull && echo ${{secrets.GIT_USERNAME}} && echo ${{secrets.GIT_TOKEN}};
            sudo docker compose down
            sudo docker compose up --build -d

