name : 'MLCity Backend develop server deploy'

on:
  push:
    branches: ["develop"]

jobs:
  re-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH }}

          script: |
            cd ${{ secrets.DEV_DIR }};
            git checkout develop;
            git pull;
            sudo docker compose down
            sudo docker compose up --build -d

